version: "3.9"

services:
  api:
    container_name: "api-clini"
    build: .
    ports:
      - 3500:3500
    depends_on:
      - db
    links:
      - "db:db"
    env_file: ".env.docker"
  db:
    container_name: "db-clini"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "clini"
      MONGO_INITDB_ROOT_PASSWORD: "clini"
    ports:
      - 5005:27017
